"""finance_updates

Revision ID: ddf07225b9bf
Revises: 20260426_pasaporte_digital
Create Date: 2026-06-03 03:11:10.580667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ddf07225b9bf'
down_revision: Union[str, Sequence[str], None] = '20260426_pasaporte_digital'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moodle_user_credentials')
    op.add_column('charges', sa.Column('discount_amount', sa.Float(), server_default='0.0', nullable=False))
    op.create_index(op.f('ix_cycle_tuitions_id'), 'cycle_tuitions', ['id'], unique=False)
    op.alter_column('grades', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('grades', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.alter_column('grades', 'status',
               existing_type=postgresql.ENUM('Cursando', 'Aprobada', 'Reprobada', 'Proximamente', name='grade_status'),
               nullable=False)
    op.drop_constraint(op.f('grades_student_id_fkey'), 'grades', type_='foreignkey')
    op.drop_constraint(op.f('grades_subject_id_fkey'), 'grades', type_='foreignkey')
    op.create_foreign_key(None, 'grades', 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'grades', 'users', ['student_id'], ['id'], ondelete='CASCADE')
    op.alter_column('notification_messages', 'target_scope',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'role'::character varying"))
    op.alter_column('notification_messages', 'category',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'general'::character varying"))
    op.alter_column('notification_messages', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.add_column('payments', sa.Column('payment_date', sa.DateTime(), nullable=True))
    payment_method_enum = postgresql.ENUM('Efectivo', 'Transferencia', 'Tarjeta', 'Deposito', name='payment_method')
    payment_method_enum.create(op.get_bind())
    op.add_column('payments', sa.Column('payment_method', payment_method_enum, nullable=True))
    op.add_column('payments', sa.Column('reference', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('is_conciliated', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('payments', sa.Column('receipt_url', sa.String(), nullable=True))
    op.alter_column('payments', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('payments', 'status',
               existing_type=postgresql.ENUM('Pendiente', 'Pagado', 'Vencido', name='payment_status'),
               nullable=False)
    op.drop_constraint(op.f('payments_student_id_fkey'), 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'users', ['student_id'], ['id'], ondelete='CASCADE')
    op.alter_column('school_cycles', 'period',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school_cycles', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('school_cycles', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('school_cycles', 'monthly_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.create_index(op.f('ix_school_cycles_id'), 'school_cycles', ['id'], unique=False)
    op.alter_column('service_requests', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('service_requests', 'status',
               existing_type=postgresql.ENUM('En Proceso', 'Listo', 'Entregado', name='service_status'),
               nullable=False)
    op.drop_constraint(op.f('service_requests_student_id_fkey'), 'service_requests', type_='foreignkey')
    op.create_foreign_key(None, 'service_requests', 'users', ['student_id'], ['id'], ondelete='CASCADE')
    op.drop_column('service_requests', 'is_support_ticket')
    op.drop_column('service_requests', 'history_json')
    op.drop_column('service_requests', 'updated_at')
    op.drop_column('service_requests', 'closed_at')
    op.drop_column('service_requests', 'source_system')
    op.drop_column('service_requests', 'description')
    op.drop_column('service_requests', 'admin_response')
    op.drop_column('service_requests', 'subject')
    op.drop_index(op.f('ix_subject_assignments_group_id'), table_name='subject_assignments')
    op.create_index(op.f('ix_subject_assignments_id'), 'subject_assignments', ['id'], unique=False)
    op.drop_index(op.f('ix_subjects_moodle_course_id'), table_name='subjects')
    op.create_unique_constraint(None, 'subjects', ['moodle_course_id'])
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('admin', 'teacher', 'student', 'services', name='user_role'),
               nullable=False)
    op.drop_constraint(op.f('users_modality_id_fkey'), 'users', type_='foreignkey')
    op.drop_constraint(op.f('users_career_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'modalities', ['modality_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'users', 'careers', ['career_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_career_id_fkey'), 'users', 'careers', ['career_id'], ['id'])
    op.create_foreign_key(op.f('users_modality_id_fkey'), 'users', 'modalities', ['modality_id'], ['id'])
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('admin', 'teacher', 'student', 'services', name='user_role'),
               nullable=True)
    op.drop_constraint(None, 'subjects', type_='unique')
    op.create_index(op.f('ix_subjects_moodle_course_id'), 'subjects', ['moodle_course_id'], unique=True)
    op.drop_index(op.f('ix_subject_assignments_id'), table_name='subject_assignments')
    op.create_index(op.f('ix_subject_assignments_group_id'), 'subject_assignments', ['group_id'], unique=False)
    op.add_column('service_requests', sa.Column('subject', sa.VARCHAR(length=180), autoincrement=False, nullable=True))
    op.add_column('service_requests', sa.Column('admin_response', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('service_requests', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('service_requests', sa.Column('source_system', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('service_requests', sa.Column('closed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('service_requests', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('service_requests', sa.Column('history_json', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('service_requests', sa.Column('is_support_ticket', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'service_requests', type_='foreignkey')
    op.create_foreign_key(op.f('service_requests_student_id_fkey'), 'service_requests', 'users', ['student_id'], ['id'])
    op.alter_column('service_requests', 'status',
               existing_type=postgresql.ENUM('En Proceso', 'Listo', 'Entregado', name='service_status'),
               nullable=True)
    op.alter_column('service_requests', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_school_cycles_id'), table_name='school_cycles')
    op.alter_column('school_cycles', 'monthly_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('school_cycles', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('school_cycles', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('school_cycles', 'period',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key(op.f('payments_student_id_fkey'), 'payments', 'users', ['student_id'], ['id'])
    op.alter_column('payments', 'status',
               existing_type=postgresql.ENUM('Pendiente', 'Pagado', 'Vencido', name='payment_status'),
               nullable=True)
    op.alter_column('payments', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('payments', 'receipt_url')
    op.drop_column('payments', 'is_conciliated')
    op.drop_column('payments', 'reference')
    op.drop_column('payments', 'payment_method')
    op.drop_column('payments', 'payment_date')
    op.alter_column('notification_messages', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('notification_messages', 'category',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'general'::character varying"))
    op.alter_column('notification_messages', 'target_scope',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'role'::character varying"))
    op.drop_constraint(None, 'grades', type_='foreignkey')
    op.drop_constraint(None, 'grades', type_='foreignkey')
    op.create_foreign_key(op.f('grades_subject_id_fkey'), 'grades', 'subjects', ['subject_id'], ['id'])
    op.create_foreign_key(op.f('grades_student_id_fkey'), 'grades', 'users', ['student_id'], ['id'])
    op.alter_column('grades', 'status',
               existing_type=postgresql.ENUM('Cursando', 'Aprobada', 'Reprobada', 'Proximamente', name='grade_status'),
               nullable=True)

    op.alter_column('grades', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('grades', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_cycle_tuitions_id'), table_name='cycle_tuitions')
    op.drop_column('charges', 'discount_amount')
    op.create_table('moodle_user_credentials',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('moodle_username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('moodle_password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password_updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('moodle_user_credentials_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('moodle_user_credentials_pkey'))
    )
    # ### end Alembic commands ###
