"""Curricula base agrupada por cuatrimestre.

Captura el valor real en `credits` cuando lo tengas.
Mientras un credito sea `None`, el sistema usa 8 por defecto.
"""

CURRICULUM_CREDITS = {
    'Ingeniería en Software': {
        '1': [
            {"name": 'Fundamentos de Ingenier\xeda de Software', "credits": None},
            {"name": '\xc1lgebra Lineal', "credits": None},
            {"name": 'Comunicaci\xf3n Oral y Escrita', "credits": None},
            {"name": 'Herramientas Tecnol\xf3gicas', "credits": None},
            {"name": 'Ingl\xe9s I', "credits": None},
        ],
        '2': [
            {"name": 'Lenguaje Unificado de Modelado', "credits": None},
            {"name": 'C\xe1lculo Diferencial', "credits": None},
            {"name": 'C\xe1lculo Integral', "credits": None},
            {"name": 'Potenciar Habilidades Humanas', "credits": None},
            {"name": 'Fundamentos de Programaci\xf3n', "credits": None},
            {"name": 'Programaci\xf3n', "credits": None},
            {"name": 'Ingl\xe9s II', "credits": None},
        ],
        '3': [
            {"name": 'Ingenier\xeda de Requerimientos', "credits": None},
            {"name": 'An\xe1lisis y Dise\xf1o de Software', "credits": None},
            {"name": 'Matem\xe1ticas Computacionales', "credits": None},
            {"name": 'L\xf3gica Digital', "credits": None},
            {"name": 'M\xe9todos Num\xe9ricos', "credits": None},
            {"name": 'Liderazgo', "credits": None},
            {"name": 'Algoritmos y Estructura de Datos', "credits": None},
            {"name": 'Ingl\xe9s III', "credits": None},
        ],
        '4': [
            {"name": 'Dise\xf1o de Interfaces', "credits": None},
            {"name": 'Modelos y Est\xe1ndares de Calidad de Software', "credits": None},
            {"name": 'Arquitectura de Computadoras', "credits": None},
            {"name": 'Probabilidad y Estad\xedstica', "credits": None},
            {"name": 'Sistemas Operativos', "credits": None},
            {"name": 'Desarrollo Personal y Profesional', "credits": None},
            {"name": 'Programaci\xf3n Orientada a Objetos', "credits": None},
            {"name": 'Ingl\xe9s IV', "credits": None},
        ],
        '5': [
            {"name": 'Proceso Personal de Software', "credits": None},
            {"name": 'Dise\xf1o de Compiladores e Int\xe9rpretes', "credits": None},
            {"name": 'Simulaci\xf3n', "credits": None},
            {"name": 'Redes I', "credits": None},
            {"name": 'Creatividad y Resoluci\xf3n de Problemas', "credits": None},
            {"name": 'Bases de Datos', "credits": None},
            {"name": 'Ingl\xe9s V', "credits": None},
        ],
        '6': [
            {"name": 'Proceso en Equipo de Software', "credits": None},
            {"name": 'Programaci\xf3n Visual', "credits": None},
            {"name": 'Redes II', "credits": None},
            {"name": 'Formulaci\xf3n de Proyectos', "credits": None},
            {"name": 'Bases de Datos Avanzadas', "credits": None},
            {"name": 'Ingl\xe9s VI', "credits": None},
        ],
        '7': [
            {"name": 'Programaci\xf3n \xc1gil', "credits": None},
            {"name": 'Pruebas y Mantenimiento de Software', "credits": None},
            {"name": 'Programaci\xf3n de Dispositivos M\xf3viles', "credits": None},
            {"name": 'Administraci\xf3n de Redes', "credits": None},
            {"name": 'Evaluaci\xf3n de Proyectos', "credits": None},
            {"name": 'Programaci\xf3n Web', "credits": None},
            {"name": 'Metodolog\xeda de la Investigaci\xf3n', "credits": None},
        ],
        '8': [
            {"name": 'M\xe9tricas de Software', "credits": None},
            {"name": 'Procesamiento Digital de Im\xe1genes', "credits": None},
            {"name": 'Direcci\xf3n de Proyectos', "credits": None},
            {"name": 'Administraci\xf3n de Bases de Datos', "credits": None},
            {"name": 'Sistemas de Soporte a la Decisi\xf3n', "credits": None},
            {"name": 'Seminario de Investigaci\xf3n I', "credits": None},
        ],
        '9': [
            {"name": 'Sistemas Integrados', "credits": None},
            {"name": 'Data Warehouse', "credits": None},
            {"name": 'Sistemas Expertos', "credits": None},
            {"name": 'Mercadotecnia', "credits": None},
            {"name": 'Adm\xf3n de Proyectos TI y Comunicaciones', "credits": None},
            {"name": 'Seminario de Investigaci\xf3n II', "credits": None},
        ],
    },
    'Ingeniería en Telemática': {
        '1': [
            {"name": 'Introducci\xf3n a las Telecomunicaciones', "credits": None},
            {"name": '\xc1lgebra Lineal', "credits": None},
            {"name": 'Comunicaci\xf3n Oral y Escrita', "credits": None},
            {"name": 'Herramientas Tecnol\xf3gicas', "credits": None},
            {"name": 'Ingl\xe9s I', "credits": None},
            {"name": 'C\xe1lculo Diferencial', "credits": None},
            {"name": 'F\xedsica', "credits": None},
        ],
        '2': [
            {"name": 'Redes de Datos', "credits": None},
            {"name": 'C\xe1lculo Integral', "credits": None},
            {"name": 'Potenciar Habilidades Humanas', "credits": None},
            {"name": 'Fundamentos de Programaci\xf3n', "credits": None},
            {"name": 'Ingl\xe9s II', "credits": None},
            {"name": 'Matem\xe1ticas Computacionales', "credits": None},
            {"name": 'Electricidad y Magnetismo', "credits": None},
        ],
        '3': [
            {"name": 'Enrutamiento B\xe1sico', "credits": None},
            {"name": 'C\xe1lculo Vectorial', "credits": None},
            {"name": 'Liderazgo', "credits": None},
            {"name": 'Algoritmos y Estructura de Datos', "credits": None},
            {"name": 'Ingl\xe9s III', "credits": None},
            {"name": 'Probabilidad y Estad\xedstica', "credits": None},
            {"name": 'Programaci\xf3n I', "credits": None},
        ],
        '4': [
            {"name": 'Enrutamiento WAN y Conmutaci\xf3n', "credits": None},
            {"name": 'Ecuaciones Diferenciales', "credits": None},
            {"name": 'Desarrollo Personal y Profesional', "credits": None},
            {"name": 'Programaci\xf3n II', "credits": None},
            {"name": 'Ingl\xe9s IV', "credits": None},
            {"name": 'Cableado Estructurado', "credits": None},
            {"name": 'Simulaci\xf3n', "credits": None},
        ],
        '5': [
            {"name": 'Comunicaciones Digitales', "credits": None},
            {"name": 'M\xe9todos Num\xe9ricos', "credits": None},
            {"name": 'Creatividad y Resoluci\xf3n de Problemas', "credits": None},
            {"name": 'Bases de Datos', "credits": None},
            {"name": 'Ingl\xe9s V', "credits": None},
            {"name": 'Sistemas Operativos y Servicios de Internet', "credits": None},
            {"name": 'Formulaci\xf3n de Proyectos', "credits": None},
        ],
        '6': [
            {"name": 'Comunicaciones \xd3pticas', "credits": None},
            {"name": 'Procesamiento Digital Se\xf1ales Comunicaci\xf3n I', "credits": None},
            {"name": 'Evaluaci\xf3n de Proyectos', "credits": None},
            {"name": 'Bases de Datos Avanzadas', "credits": None},
            {"name": 'Ingl\xe9s VI', "credits": None},
            {"name": 'Comunicaciones M\xf3viles y Satelitales', "credits": None},
            {"name": 'Modelos y Est\xe1ndares de Calidad Software', "credits": None},
        ],
        '7': [
            {"name": 'Voz/IP', "credits": None},
            {"name": 'Proc. Digital Se\xf1ales Comunicaci\xf3n II', "credits": None},
            {"name": 'Direcci\xf3n de Proyectos', "credits": None},
            {"name": 'Ingenier\xeda de Software I', "credits": None},
            {"name": 'Metodolog\xeda de la Investigaci\xf3n', "credits": None},
            {"name": 'Seguridad en Redes', "credits": None},
            {"name": 'Procesamiento Digital de Im\xe1genes', "credits": None},
        ],
        '8': [
            {"name": 'Administraci\xf3n de Redes', "credits": None},
            {"name": 'Servicio Social', "credits": None},
            {"name": 'Ingenier\xeda de Software II', "credits": None},
            {"name": 'Seminario de Investigaci\xf3n I', "credits": None},
        ],
        '9': [
            {"name": 'Redes Inal\xe1mbricas de Sensores', "credits": None},
            {"name": 'Mercadotecnia', "credits": None},
            {"name": 'Adm\xf3n. Proyectos de TI y Comunicaciones', "credits": None},
            {"name": 'Seminario de Investigaci\xf3n II', "credits": None},
            {"name": 'Calidad de Servicio', "credits": None},
        ],
    },
    'Preparatoria': {
        '1': [
            {"name": 'Matem\xe1ticas I', "credits": None},
            {"name": 'Qu\xedmica I', "credits": None},
            {"name": '\xc9tica y Valores I', "credits": None},
            {"name": 'Introd. a las Ciencias Sociales', "credits": None},
            {"name": 'Taller de Lectura y Redacci\xf3n I', "credits": None},
            {"name": 'Lengua Adicional al Espa\xf1ol I', "credits": None},
            {"name": 'Inform\xe1tica I', "credits": None},
            {"name": 'Arte y Dise\xf1o', "credits": None},
        ],
        '2': [
            {"name": 'Matem\xe1ticas II', "credits": None},
            {"name": 'Qu\xedmica II', "credits": None},
            {"name": '\xc9tica y Valores II', "credits": None},
            {"name": 'Historia de M\xe9xico I', "credits": None},
            {"name": 'Taller de Lectura y Redacci\xf3n II', "credits": None},
            {"name": 'Lengua Adicional al Espa\xf1ol II', "credits": None},
            {"name": 'Inform\xe1tica II', "credits": None},
            {"name": 'Expresi\xf3n Corporal', "credits": None},
        ],
        '3': [
            {"name": 'Matem\xe1ticas III', "credits": None},
            {"name": 'Geograf\xeda', "credits": None},
            {"name": 'F\xedsica I', "credits": None},
            {"name": 'Historia de M\xe9xico II', "credits": None},
            {"name": 'Literatura I', "credits": None},
            {"name": 'Lengua Adicional al Espa\xf1ol III', "credits": None},
            {"name": 'Aplica. Gr\xe1ficas con Prog. Integrados', "credits": None},
            {"name": 'Sistemas de Informaci\xf3n I', "credits": None},
            {"name": 'Com. Asertiva y Toma de Decisiones', "credits": None},
        ],
        '4': [
            {"name": 'Matem\xe1ticas IV', "credits": None},
            {"name": 'Biolog\xeda I', "credits": None},
            {"name": 'F\xedsica II', "credits": None},
            {"name": 'Estructura Socioecon\xf3mica de M\xe9x.', "credits": None},
            {"name": 'Literatura II', "credits": None},
            {"name": 'Lengua Adicional al Espa\xf1ol IV', "credits": None},
            {"name": 'Aplic. Espec\xedficas Prog. Integrados', "credits": None},
            {"name": 'Sistemas de Informaci\xf3n II', "credits": None},
            {"name": 'Orientaci\xf3n Vocacional', "credits": None},
        ],
        '5': [
            {"name": 'Biolog\xeda II', "credits": None},
            {"name": 'Hist. Universal Contempor\xe1nea', "credits": None},
            {"name": 'C\xe1lculo Diferencial', "credits": None},
            {"name": 'Dibujo I', "credits": None},
            {"name": 'Temas Selectos de F\xedsica I', "credits": None},
            {"name": 'Probabilidad y Estad\xedstica I', "credits": None},
            {"name": 'L\xf3gica Computacional y Programaci\xf3n', "credits": None},
            {"name": 'Bases de Datos I', "credits": None},
            {"name": 'Negociaci\xf3n p/ Soluci\xf3n de Conflictos', "credits": None},
        ],
        '6': [
            {"name": 'Filosof\xeda', "credits": None},
            {"name": 'Ecolog\xeda y Medio Ambiente', "credits": None},
            {"name": 'Metodolog\xeda de la Investigaci\xf3n', "credits": None},
            {"name": 'C\xe1lculo Integral', "credits": None},
            {"name": 'Dibujo II', "credits": None},
            {"name": 'Temas Selectos de F\xedsica II', "credits": None},
            {"name": 'Probabilidad y Estad\xedstica II', "credits": None},
            {"name": 'Introducci\xf3n a las Redes', "credits": None},
            {"name": 'Bases de Datos II', "credits": None},
            {"name": 'Cultura F\xedsica', "credits": None},
        ],
    },
}
